//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FinancialCalculator.mortgageCalculation1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Mortgage CalculatorBinding", Namespace="urn:soaptest")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AmortizationSchedule))]
    public partial class MortgageCalculator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_mortgageOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_totalinterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback create_amortizationscheduleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MortgageCalculator() {
            this.Url = "http://192.168.1.219/IT140P_MP/mortgageservice.php";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_mortgageCompletedEventHandler get_mortgageCompleted;
        
        /// <remarks/>
        public event get_totalinterestCompletedEventHandler get_totalinterestCompleted;
        
        /// <remarks/>
        public event create_amortizationscheduleCompletedEventHandler create_amortizationscheduleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/IT140P/FinancialCalc/service.php#get_mortgage", RequestNamespace="http://localhost/IT140P/FinancialCalc/service.php", ResponseNamespace="http://localhost/IT140P/FinancialCalc/service.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("monthlyPayment")]
        public double get_mortgage(double loanAmount, double interestRate, int loanTerm) {
            object[] results = this.Invoke("get_mortgage", new object[] {
                        loanAmount,
                        interestRate,
                        loanTerm});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_mortgageAsync(double loanAmount, double interestRate, int loanTerm) {
            this.get_mortgageAsync(loanAmount, interestRate, loanTerm, null);
        }
        
        /// <remarks/>
        public void get_mortgageAsync(double loanAmount, double interestRate, int loanTerm, object userState) {
            if ((this.get_mortgageOperationCompleted == null)) {
                this.get_mortgageOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_mortgageOperationCompleted);
            }
            this.InvokeAsync("get_mortgage", new object[] {
                        loanAmount,
                        interestRate,
                        loanTerm}, this.get_mortgageOperationCompleted, userState);
        }
        
        private void Onget_mortgageOperationCompleted(object arg) {
            if ((this.get_mortgageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_mortgageCompleted(this, new get_mortgageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/IT140P/FinancialCalc/service.php#get_totalinterest", RequestNamespace="http://localhost/IT140P/FinancialCalc/service.php", ResponseNamespace="http://localhost/IT140P/FinancialCalc/service.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("totalInterest")]
        public double get_totalinterest(double loanAmount, double interestRate, int loanTerm) {
            object[] results = this.Invoke("get_totalinterest", new object[] {
                        loanAmount,
                        interestRate,
                        loanTerm});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void get_totalinterestAsync(double loanAmount, double interestRate, int loanTerm) {
            this.get_totalinterestAsync(loanAmount, interestRate, loanTerm, null);
        }
        
        /// <remarks/>
        public void get_totalinterestAsync(double loanAmount, double interestRate, int loanTerm, object userState) {
            if ((this.get_totalinterestOperationCompleted == null)) {
                this.get_totalinterestOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_totalinterestOperationCompleted);
            }
            this.InvokeAsync("get_totalinterest", new object[] {
                        loanAmount,
                        interestRate,
                        loanTerm}, this.get_totalinterestOperationCompleted, userState);
        }
        
        private void Onget_totalinterestOperationCompleted(object arg) {
            if ((this.get_totalinterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_totalinterestCompleted(this, new get_totalinterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/IT140P/FinancialCalc/service.php#create_amortizationschedule", RequestNamespace="http://localhost/IT140P/FinancialCalc/service.php", ResponseNamespace="http://localhost/IT140P/FinancialCalc/service.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("amortizationSchedule")]
        public AmortizationSchedule[] create_amortizationschedule(double loanAmount, double interestRate, int loanTerm, double monthlyPayment) {
            object[] results = this.Invoke("create_amortizationschedule", new object[] {
                        loanAmount,
                        interestRate,
                        loanTerm,
                        monthlyPayment});
            return ((AmortizationSchedule[])(results[0]));
        }
        
        /// <remarks/>
        public void create_amortizationscheduleAsync(double loanAmount, double interestRate, int loanTerm, double monthlyPayment) {
            this.create_amortizationscheduleAsync(loanAmount, interestRate, loanTerm, monthlyPayment, null);
        }
        
        /// <remarks/>
        public void create_amortizationscheduleAsync(double loanAmount, double interestRate, int loanTerm, double monthlyPayment, object userState) {
            if ((this.create_amortizationscheduleOperationCompleted == null)) {
                this.create_amortizationscheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncreate_amortizationscheduleOperationCompleted);
            }
            this.InvokeAsync("create_amortizationschedule", new object[] {
                        loanAmount,
                        interestRate,
                        loanTerm,
                        monthlyPayment}, this.create_amortizationscheduleOperationCompleted, userState);
        }
        
        private void Oncreate_amortizationscheduleOperationCompleted(object arg) {
            if ((this.create_amortizationscheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.create_amortizationscheduleCompleted(this, new create_amortizationscheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:soaptest")]
    public partial class AmortizationSchedule {
        
        private int paymentNumberField;
        
        private double interestField;
        
        private double principalField;
        
        private double totalAmountField;
        
        private double balanceField;
        
        /// <remarks/>
        public int paymentNumber {
            get {
                return this.paymentNumberField;
            }
            set {
                this.paymentNumberField = value;
            }
        }
        
        /// <remarks/>
        public double interest {
            get {
                return this.interestField;
            }
            set {
                this.interestField = value;
            }
        }
        
        /// <remarks/>
        public double principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        public double totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        public double balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_mortgageCompletedEventHandler(object sender, get_mortgageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_mortgageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_mortgageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_totalinterestCompletedEventHandler(object sender, get_totalinterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_totalinterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_totalinterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void create_amortizationscheduleCompletedEventHandler(object sender, create_amortizationscheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class create_amortizationscheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal create_amortizationscheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AmortizationSchedule[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AmortizationSchedule[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591