//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FinancialCalculator.investCalc {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Investment CalculatorBinding", Namespace="urn:soaptest")]
    public partial class InvestmentCalculator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback calculate_final_amountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InvestmentCalculator() {
            this.Url = "http://192.168.1.219/IT140P_MP/investservice.php";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event calculate_final_amountCompletedEventHandler calculate_final_amountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://192.168.1.219/IT140P_MP/investservice.php/calculate_final_amount", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string calculate_final_amount(decimal startingAmount, decimal yearsToGrow, decimal returnRate, decimal additionalContribution, string contributionTiming) {
            object[] results = this.Invoke("calculate_final_amount", new object[] {
                        startingAmount,
                        yearsToGrow,
                        returnRate,
                        additionalContribution,
                        contributionTiming});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calculate_final_amountAsync(decimal startingAmount, decimal yearsToGrow, decimal returnRate, decimal additionalContribution, string contributionTiming) {
            this.calculate_final_amountAsync(startingAmount, yearsToGrow, returnRate, additionalContribution, contributionTiming, null);
        }
        
        /// <remarks/>
        public void calculate_final_amountAsync(decimal startingAmount, decimal yearsToGrow, decimal returnRate, decimal additionalContribution, string contributionTiming, object userState) {
            if ((this.calculate_final_amountOperationCompleted == null)) {
                this.calculate_final_amountOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncalculate_final_amountOperationCompleted);
            }
            this.InvokeAsync("calculate_final_amount", new object[] {
                        startingAmount,
                        yearsToGrow,
                        returnRate,
                        additionalContribution,
                        contributionTiming}, this.calculate_final_amountOperationCompleted, userState);
        }
        
        private void Oncalculate_final_amountOperationCompleted(object arg) {
            if ((this.calculate_final_amountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculate_final_amountCompleted(this, new calculate_final_amountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void calculate_final_amountCompletedEventHandler(object sender, calculate_final_amountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculate_final_amountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculate_final_amountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591